spring.profiles:
  group:
    "local": "common, local"
  active: local
---
spring:
  config.activate.on-profile: "common"
  application:
    name: Security
    desc: 통합인증
  output.ansi.enabled: ALWAYS
  thymeleaf.cache: false

server:
  servlet.encoding.charset: UTF-8
  error.whitelabel.enabled: false
  port: 11002

logging:
  level:
    org.apache.coyote.http11: debug