spring.profiles:
  group:
    "local": "common, local"
  active: local
---
spring:
  config.activate.on-profile: "common"
  application:
    name: Security
    desc: 통합인증
  output.ansi.enabled: ALWAYS
  # 아이디 비밀번호
  security.user:
      name: user
      password: 1234
  thymeleaf:
    cache: false

server:
  servlet.encoding.charset: UTF-8
  error.whitelabel.enabled: false
  port: 11002

  ssl:
    enable: false
#    key-store: keystore.p12
#    key-store-password: tngus12
#    key-store-type: PKCS12
#    key-alias: bns-ssl

logging:
  level.org.apache.coyote.http11: debug
